### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#12]
The CoinGreen icon is attached here

**Comment by MarkH24** [comment]
![cg-logo-final-2](https://user-images.githubusercontent.com/66521553/130988078-c59c2762-06f6-41fc-9dbf-c717ad3f7e6a.png)

**Comment by MarkH24** [comment]
Can we us this image for CoinGreen?

**Comment by maxirmx** [comment]
Yes, I will do it.

**Comment by maxirmx** [comment]
Closed by https://github.com/coin-green/CoinGreen/pull/1
