### ISSUE TITLE
Satoshi per byte - rename

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#17]
There should be similar to Bitcoin also in Dogecoin be a kind of "coin" currency smaller than 1 bitcoin. Currently names as Satoshis.

1/100,000,000 BITCOIN = 1 Satoshi

I would like to rename Satoshi to GreenLeaves.

So 1/100,000,000 GreenLeaves = 1 CoinGreen

**Comment by maxirmx** [comment]
In Dogecoin there is no currency smaller than 1 dogecoin. 
Everything that is smaller is considered 'dust'

**Comment by maxirmx** [comment]
I will rename Satoshi to GreenLeaves in the next build.
What shall be considered 'dust' ?

**Comment by maxirmx** [comment]
Closed with
https://github.com/coin-green/CoinGreen/releases/tag/v2.0.0.3
