### ISSUE TITLE
Port for CoinGreen currently is 22556 - this is the same as Dogecoin

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#19]
I fear that this may cause some issue if people will run doge and coingreen. Bitcoins it seems has 8333 and 18333. So I suggest to change this to lets say 34558

**Comment by maxirmx** [comment]
Will do in the next build

**Comment by maxirmx** [comment]
Closed with
https://github.com/coin-green/CoinGreen/releases/tag/v2.0.0.3
