### ISSUE TITLE
How is the private key created and stored? 

### ISSUE THREAD

**Issue by maxirmx** [coin-green/genesis#2]
How is the private key created and stored?

**Comment by maxirmx** [comment]
Private key is generated using [Secp256k1](https://en.bitcoin.it/wiki/Secp256k1)
It is stored in a wallet file

**Comment by MarkH24** [comment]
Could this be used also in a mobile wallet?

**Comment by maxirmx** [comment]
There are several wallet applications.  They use different files to store account information, including keys.

Please have a look at this one:  https://play.google.com/store/apps/details?id=de.langerhans.wallet&hl=en&gl=US   It is developed  by another group of people, not those who created dogecoin core and reference wallet.

It is separate application that can be also ported to support CoinGreen.
