### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#20]
Which file contained the GUI?

**Comment by maxirmx** [comment]
I am sorry, I do not understand the question.   
If you ask about executable, it is _coingreen-gui.exe_

**Comment by maxirmx** [comment]
If you ask how to start GUI, for the last version call _coingreen.bat_  It will start GUI and connect to network automatically.

**Comment by MarkH24** [comment]
No what I meant is the layout of the GUI - that should be customizable within a file...

**Comment by maxirmx** [comment]
Here
https://github.com/coin-green/CoinGreen/tree/master/src/qt/forms

You will need Qt designer
