### ISSUE TITLE
New version upgrade

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#21]
What is the right way to migrate from one version to another?

1) save the private key
2) uninstall old version
3) install new version
4) import private key?

Could there be also an "update" option to void these steps?

**Comment by maxirmx** [comment]
No need to make any manipulations with private key. Delete old version, install new one.
Do not touch data directory, your wallet is there and new version will load it.

**Comment by MarkH24** [comment]
Even if I selected a directory deviating from the default one?

**Comment by maxirmx** [comment]
Even if you selected a directory deviating from the default one you do not need export\import private key to upgrade.

You transactions may be invalidated and lost though but it is not because of private key and data migration.  Your chain is now orphant and  the other four nodes (two network and two clients that I run) may decide to disacard it.   The more you wait the more probable this outcome becomes.  This is 51% attack you were asking about.

**Comment by maxirmx** [comment]
**From @MarkH24:** 
Regarding the 3 modules you proposed.
If I just want to buy or own CG I can still just download the current wallet software? 

**Reply:**
Well, you need the version of sofware that is compatible with consensus algorithm that is accepted by the majority of nodes.
Practically it means, that most of the time you do not need specially care about your client version.
However, sometimes majority of community agrees to change consensus rules. In that case everyone who wants to stay in the game shall upgrade.

**Comment by MarkH24** [comment]
ok upgrade completed - so far it seems to be running fine

**Comment by MarkH24** [comment]
if I enter "generate 1" thats seems to be stuck sometimes in execution. It either shows no result after execution or shows the block - but I dont understand when and if it generate the block or when it doesnt

**Comment by maxirmx** [comment]
> if I enter "generate 1" thats seems to be stuck sometimes in execution. It either shows no result after execution or shows the block - but I dont understand when and if it generate the block or when it doesnt

Full command is 
**generate nblocks ( maxtries )**

It mines up to _nblocks_ blocks immediately making up to _maxtries_ attempts

Result:
[ blockhashes ]     (array) hashes of blocks generated


So
if _generate 1_   ends with empty array  
_[  
]_    
it means that it failed to find a hash in default number of attempts  (1000000)
you may try bigger numner of attempts, i.e. something like   _generate 1 30000000_

if _generate 1_   shows the block 
something like 
_[
  "c6d72d580ad016a35ad1cb08de8a7015eb69e832764e7a7400d7596135a2ee60"
]_
it means it has found a hash and has generated a block.

**Comment by maxirmx** [comment]
> ok upgrade completed - so far it seems to be running fine

Yes, now my transactions confirm your and vise versa.  The previous version coulkd not do it.
