### ISSUE TITLE
Multi miner

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#22]
If there run several miners at the same time
- who will get the reward 
- can we see who mined the block

**Comment by maxirmx** [comment]
- If there are several miners reward is given to the one who has the longest chain.
Practically if blockchain is wealthy it means that reward is given to the miner who published the new block first.
All nodes operate on a simple rule: always trust the longest chain of blocks. If a node received two "next blocks", it will save both and start to work on the next block in one of the chains. If in the meantime it receives a new block for one of the chains, it will discard the shorter chain and start to work on a next block for the longer chain.

- In the blockchain there is no secrets. You can see who mined the block
