### ISSUE TITLE
Permanent miner

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#25]
can we make one node be a permanent miner running the script all the time so we get transactions confiremd quickly?

How many miners will we need to bring down confirmation times to the lowest possible?

**Comment by maxirmx** [comment]
Yes, one node can be a permanent miner.

I did not find the answer for your second question for any of well established blockchains. I looks like no one thinks your way.

Generally speaking, there is no guaranteed confirmation time in the blockchain. It is like driving down a freeway. A high number of transactions means there's going to be a lot of congestion, slowing everything down. Paying bigger transaction fees moves transaction  to the front of the queue and delays all other transactions.

**Comment by MarkH24** [comment]
ok - my question relates to the fact that I currently need to make about 80 blocks manually to get one transfer completed.

So guess this is related to the consensus aspect and requires either more nodes / miners at the same time to confirma a transaction several times or even simple more blocks within the same engine.

Maybe I think in the wrong direction and you can bring some more light into my understanding of the blockchain.

My goal would be to get the transaction comfirmed within a few mins. If I assume currently we make a block every minute and I have to generate 80 blocks at the moment to get one transfer done, I would have to wait for 80 mins which is by far to long.

**Comment by MarkH24** [comment]
lets start here with one permanent miner if possible short term...

**Comment by maxirmx** [comment]
I found very simple standalone miner that can be adopted for CoinGreen
https://github.com/ricmoo/nightminer

If changed to mine CoinGreen it can be installed at virtually any hardware.  Looking ahead it will be reference implementation for high performance stand-alone miner. This code can be adopted  in 15-20 hours (including testing) and installed  to one of network nodes running permanently.

I have some doubts about 80 blocks.  If you have mature coins in your wallet,  the fasted possible confirmation is 2 blocks.  So the lowest possible time is 2 minutes.

**Comment by maxirmx** [comment]
Pls confirm 15-20 hours for permanent miner

**Comment by maxirmx** [comment]
We now have permanent miner running at Jupitan host (35.183.50.52)
It is cpuminer 2.5.1 that can be downloaded from https://github.com/coin-green/CoinGreen/releases/tag/v2.0.0.4
Configuration is here: https://github.com/coin-green/genesis/tree/main/cpuminer (Top secret, no public access)
