### ISSUE TITLE
5 miners - revenue distribution

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#29]
In case more miners start to work in CoinGreen - do we know anything about revenue distribution? I guess thats most likely somewhere governed within the code.

**Comment by maxirmx** [comment]
The blockchain nodes do not do any revenue distribution.  Whoever find the hash first receives all revenues.
I think you mean mining pool software and the distribution can be configured in it.

**Comment by maxirmx** [comment]
Duplicates #22
