### ISSUE TITLE
Is it possible to export the private key?

### ISSUE THREAD

**Issue by maxirmx** [coin-green/genesis#3]
Is it possible to export the private key?

**Comment by maxirmx** [comment]
Yes, it is possible to export and import private key.

**General comments:**
- the software that I have ported as the first CoinGreen implementation is the original bitcoin implementation which is slightly adjusted to be dogecoin reference implementation which is further adjusted to be CoinGreen
- this software is really a command-line utility wrapped into very thin GUI
- Gui provides for just a several basic functions,   most of the capabilities are available through embedded console
- console is slightly adjusted bitcoin console. There is good online help [here](https://bitcoincore.org/en/doc/0.16.0/rpc/)

**How to export private key**

~~1. Start the client~~
~~2. Open console - select Help/Debug windows/Console~~
~~3. In the command prompt enter _'listaccounts'_   that will give you one or more accounts~~
~~4. In the command prompt enter _'getaddressesbyaccount  <account>'_  that will give you an address for selected account~~
~~5. In the command prompt enter _'dumpprivkey  <address>'_~~

Up-to-date manual is here:
https://www.reddit.com/r/dogecoin/wiki/dogecoincoreguide/

**Comment by MarkH24** [comment]
Ok

**Comment by MarkH24** [comment]
Some wallets use see phrases. This could be added here too?

**Comment by maxirmx** [comment]
Yes, this can be added

**Comment by maxirmx** [comment]
https://www.reddit.com/r/dogecoin/wiki/dogecoincoreguide/
