### ISSUE TITLE
generate 1

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#33]
Possible to see what will be executed if I enter generate 1 in the command line window?

**Comment by maxirmx** [comment]
if you enter generate 1 in the command line window it will execute
**_generate_** in https://github.com/coin-green/CoinGreen/blob/master/src/rpc/mining.cpp
and then 
**_generateBlocks_** in https://github.com/coin-green/CoinGreen/blob/master/src/rpc/mining.cpp
