### ISSUE TITLE
syncronization remains always a few days behind

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#36]
If I currently open the app and let past blocks sync, it shows it is a few days behind. If I now close and reopen the app, it shows again it is a few days behind. I seems it is not updating the blockchain in the node currently.

**Comment by maxirmx** [comment]
It is not about network syncronization.
The node that was mining ran out of disk space since it was writing logs for a couple of months. So the miner stopped and there was no new transactions for a week or so.

60 GB for a node with miner is awfully small disk
