### ISSUE TITLE
Whiche files may be available as open source

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#37]
I was woundering whether we could keep some files available for open source development by third parties. I am looking here for an advise from your side, whether you consider this to be a good idea, where you have any objections and potentially which part of the files could be made available as open source.

**Comment by maxirmx** [comment]
All files are now private
If everything is open source other people will be able to build software and contribute to development.
There is no value in making open source some of the files.  Making single file private effectively prohibits  third-party contribution
