### ISSUE TITLE
Miner auto restart

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#38]
We should have an auto miner restart option

**Comment by maxirmx** [comment]
The miner is now configured to start automatically upon system boot and restart hour check if not running
![crontab@jupitan](https://user-images.githubusercontent.com/2081498/152650330-278e5378-0004-4e07-8faa-ec32f5cfbfe4.jpg)

(at jupitan.coingreen.tech) 
This configuration uses crontab service, accessible via crontab -e

Config scripts are here: https://github.com/coin-green/genesis/tree/main/cpuminer
