### ISSUE TITLE
Is it possible to either run a node or a miner?

### ISSUE THREAD

**Issue by maxirmx** [coin-green/genesis#4]
Is it possible to either run a node or a miner?

**Comment by maxirmx** [comment]
Dogecoin reference implementation is generic. It contains all functional blocks: full node, miner and wallet.  It can be built with or without GUI\wallet, but not without miner.
CoinGreen was created from dogecoin reference implementation. So the CoinGreen application that I have is also generic and includes everything.   It can be built with or without GUI\wallet, but not without miner.

There are other applications that adhere to dogecoin protocal and implement different subsets of functions.  
For example:
- Fully functional wallet application (just one of !!!) - [multidoge] (https://multidoge.org/)
- Stand alone dogecoin miner (just one of !!!) - [DDD](https://github.com/thegoddambatman/diy-dogecoin-digger)
- other applications, such as sites that show blockchain history

**Comment by MarkH24** [comment]
Do you know why the miner is essential? In ethereum you can run also a node only.

**Comment by maxirmx** [comment]
I do not think that the miner is essential.  That's the way original "Satoshi" code was structured.
It is possible to create node executable without a miner with limited effort.  I can do it if necessary.

**Comment by maxirmx** [comment]
I think #25 closes this problem
