### ISSUE TITLE
 How can we test the consensus of the blockchain ?

### ISSUE THREAD

**Issue by maxirmx** [coin-green/genesis#5]
How can we test the consensus of the blockchain ?

**Comment by maxirmx** [comment]
I am not sure I understand the question
There is a test set that checks consensus it is [here](https://github.com/maxirmx/CoinGreen/blob/master/src/test/coingreen_tests.cpp)

**Comment by MarkH24** [comment]
My question was in the sense whether consensus needs a certain number of nodes and also whether there is any test setup. Seems it is there if I get your link correctly.
