### ISSUE TITLE
Whitelisting - is it possible to have here a kind of certificate we issue and that needs to be added to the miner - then only mining is enabled ?

### ISSUE THREAD

**Issue by maxirmx** [coin-green/genesis#6]
Whitelisting - is it possible to have here a kind of certificate we issue and that needs to be added to the miner - then only mining is enabled ?

**Comment by maxirmx** [comment]
No, I do not think it is possible.
What we discussed before was a certificate that is required to join the network - either as a node, or as a wallet, or miner or other application.
Now it looks like you are talking about something like [MultiChain](https://www.multichain.com/). Sure, it is possible to build this type of functionality on top of dogecoin, but it is not an assignment for a single person.  

Maybe it is worth to start from community version of MultiChain and not from dogecoin ?

**Comment by MarkH24** [comment]
The certificate solution is still fine. I just asked as I guess dogecoin by default has a whitelist option.

**Comment by maxirmx** [comment]
Several relevant articles are attached:

- [MultiChain-White-Paper.pdf](https://github.com/coin-green/genesis/files/7116895/MultiChain-White-Paper.pdf)
- [A_Review_of_consensus_protocols_in_permissioned_bl.pdf](https://github.com/coin-green/genesis/files/7116897/A_Review_of_consensus_protocols_in_permissioned_bl.pdf)

MultiChain WhitePaper describes an approach that can be adopted to CoinGreen since MultiChain  (1) is open source and (2) is bitcoin fork as coingreen.  
Paragraph "Mining in MultiChain"  / pages 7,8 describes some specifics related to mining permissioned network.

However it worth noting that MultiChain is an effort supported by development organization which required two attempts to deploy a viable product.

I would estimate the minimal effor required to adopt MultChain permission scheme into CoinGreen  as 300 man*hours.

**Comment by maxirmx** [comment]
bitcoin is single rank with proof of work consensus meaning that all members have equal rights
bitcoin is designed and implemented in such way that these two limitations can not be lifted

To do reliably what you want you need some kind of permission or approval system that implies multi-rank design - either permission system or special nodes that have the right to approve ot disapprove transactions.

A lot of ledgers designed and implemented after bitcoin  have some extra capabilities. For example, as far as I know etherium can be extended support permission control

The third generation (those that came after etherium) have  'corporate' capabilities built-in
