### ISSUE TITLE
changes to the number of coins and mining reward

### ISSUE THREAD

**Issue by maxirmx** [coin-green/genesis#7]
If we want to make changes like number of coins - this can be done any time or required the resetup of the blockchain ?

**Comment by maxirmx** [comment]
This or similar change will require a new version of software and the change will occur only if majority of nodes update to the new version.

Resetup of the blockchain is not required.  In fact Dogecoin changed reward scheme and PoW method several times without resetup of the blockchain

**Comment by MarkH24** [comment]
So I can give you here any number of coins and rewards and you can update this?

**Comment by maxirmx** [comment]
Yes, I can implement any reasonable reward scheme.

**Comment by maxirmx** [comment]
total supply of tokens 210,000,000
Initial supply - 43,000,000
and mining reward per block 230

**Comment by MarkH24** [comment]
we need to correct mining per block - should be 23 only as we have a block every minute and not only every 10mins like in Bitcoin

**Comment by maxirmx** [comment]
Closed with
https://github.com/coin-green/CoinGreen/pull/6
