### ISSUE TITLE
And in principle we would need then a way to access transactions on a node so we can display them like in etherscan 

### ISSUE THREAD

**Issue by maxirmx** [coin-green/genesis#9]
And in principle we would need then a way to access transactions on a node so we can display them like in etherscan

**Comment by maxirmx** [comment]
It is just a special application, "extended wallet"  like [this one](https://dogechain.info/) 
They provide a web-based wallet as well.

**Comment by MarkH24** [comment]
What do you mean with special application - I guess it is just a website using an available transaction api.

**Comment by maxirmx** [comment]
We have coingreen explorer at http://pluto.coingreen.tech:8080/
